[providers]
python = true
node = true

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs"]

[phases.build]
cmds = ["npm install", "npm run build", "cd server && npm install", "pip install requests beautifulsoup4 python-dotenv ddgs premailer html2text"]

[start]
cmd = "cd server && node index.js"
